### ISSUE TITLE
 Octopus Deploy: Failed status is treated as "Running"

### ISSUE THREAD

**Issue by ryanrousseau** [duckhq/duck#108]
**Describe the bug**
A failed Octopus Deploy task continues to show as "Running".

**To Reproduce**
1. Configure a Duck instance with an Octopus Deploy collector.
2. Change the status of the Octopus task shown in Duck to "Failed". This can be done on the deployment details page in Octopus.
3. View the Duck dashboard.
4. See that the task is running, not failed.

**Expected behavior**
A failed Octopus deployment should appear as failed in Duck.

**Additional context**
It looks like the cause is here: https://github.com/duckhq/duck/blob/master/src/providers/collectors/octopus/mod.rs#L174

"Failed" is in the list of statuses that map to "Running". The fix should be removing "Failed" from that list and letting the wildcard catch it and map it to failed.

I can use this issue as an opportunity to get my dev environment set up for Duck and submit a PR.

**Comment by patriksvensson** [comment]
@ryanrousseau Great catch! Funny thing is that we've been using this in prod for quite a while and for some reason I've never seen this before. Probably because Octopus does such an awesome job and we almost have any failed deployments.

Looking forward to the pull request. Reach out if you run into any problems!

**Comment by ryanrousseau** [comment]
Luckily my home lab is still in the early stages so I run into failures a bit more often than usual :D

Local dev setup was very smooth. The only trouble I ran into was that the duck-ui container didn't start up when running `docker-compose up` the first time, but I think that was just a fluke. It's worked fine since then. PR incoming 👍
