### ISSUE TITLE
Run Duck as a Windows Service

### ISSUE THREAD

**Issue by patriksvensson** [duckhq/duck#83]
**Is your feature request related to a problem? Please describe.**
Would be nice to be able to run Duck as a Windows Service

**Comment by gep13** [comment]
@patriksvensson if you go down the route of creating a Chocolatey Package for Duck, then running as a Windows Service is something that you could setup within the package.

**Comment by patriksvensson** [comment]
@gep13 Thanks for the info, but this is something I don't want to leave to the package manager. I want this to be purely opt-in and done within the executable, probably with an `install` command.

**Comment by gep13** [comment]
Fair enough.  In which case, if/when you do create the `install` command, you could add a package parameter to the Chocolatey Package, to allow the execution of that command at the point of installation.

**Comment by patriksvensson** [comment]
@gep13 Will absolutely do that! :+1:
