### ISSUE TITLE
Scrollbar is always visible

### ISSUE THREAD

**Issue by patriksvensson** [duckhq/duck#94]
**Describe the bug**
Would be nice if we could hide the scroll bar if it's not needed.

**Screenshots**
![image](https://user-images.githubusercontent.com/357872/80195640-74806800-861c-11ea-8238-5962cc5ce9fd.png)

**Comment by garymcleanhall** [comment]
Hmm, just like the dark mode issue - I can't replicate this, either: 

![image](https://user-images.githubusercontent.com/1361856/80300002-e1b50a00-8790-11ea-86bc-926acf8ef025.png)

**Comment by patriksvensson** [comment]
I see this in Edge on Windows and on Chromium on the Raspberry Pi. Will see if I can submit a fix later today.
