### ISSUE TITLE
White border around UI in dark mode

### ISSUE THREAD

**Issue by patriksvensson** [duckhq/duck#99]
**Describe the bug**
There's a white border around the UI in dark mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/357872/80293610-e792f700-8760-11ea-9098-772e1d25f743.png)

**EDIT**
I've narrowed the problem down to the release build (`npm run build`) and purgecss. If purgecss is removed from `postcss.config.js` it seems to work as expected.

**Comment by garymcleanhall** [comment]
How odd - I don't have that. Tested in Firefox and Chrome and neither of them have it. Looks like chrome on windows in your screenshot?

![image](https://user-images.githubusercontent.com/1361856/80299930-5176c500-8790-11ea-9617-85dfa98a6fa7.png)

**Comment by patriksvensson** [comment]
@garymcleanhall It’s Edge on Windows but could recreate it in Firefox on Arch as well. Perhaps something went wrong in the merge.

**Comment by patriksvensson** [comment]
@garymcleanhall The problem only seem to happen when embedding the web UI, not when running it stand-alone or in docker. Will try to figure out why this happen.

**Comment by patriksvensson** [comment]
@garymcleanhall Ok, it seems to happen when building with `npm run build`. It works as expected when running `npm run serve`.

**Comment by patriksvensson** [comment]
@garymcleanhall I narrowed it down to purgecss. When removing it from postcss.config.js, it looks like it should look. Should we remove purgecss until we've solved it?
